# Generated by Django 3.0.7 on 2020-07-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='User',
        ),
    ]
